version: "3.2"
services:
    gost:
        container_name: shenandoah-gost
        environment:
            GOST_SERVER_NAME: Shenandoah
            GOST_SERVER_EXTERNAL_URI: http://shenandoah:28080
        networks:
            frontend:
                ipv4_address: 172.190.0.5
    dashboard:
        container_name: shenandoah
    node-red:
        container_name: shenandoah-node-red
    mosquitto:
        container_name: shenandoah-mosquitto
        networks:
            frontend:
                ipv4_address: 172.190.0.10
            backend:
                ipv4_address: 172.191.0.10
    gost-db:
        container_name: shenandoah-gost-db
networks:
    frontend:
        ipam:
            driver: default
            config:
                - subnet: "172.190.0.0/16"
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.191.0.0/16"
