version: "3.2"
services:
    gost:
        container_name: denali-gost
        environment:
            GOST_SERVER_NAME: Denali
            GOST_SERVER_EXTERNAL_URI: http://denali:18120
        networks:
            frontend:
                ipv4_address: 172.120.0.5
    dashboard:
        container_name: denali
        ports:
            - target: 8080
              published: 18120
              protocol: tcp
              mode: host
            - target: 1880
              published: 18121
              protocol: tcp
              mode: host
    node-red:
        container_name: denali-node-red
    mosquitto:
        container_name: denali-mosquitto
        networks:
            frontend:
                ipv4_address: 172.120.0.10
            backend:
                ipv4_address: 172.121.0.10

    gost-db:
        container_name: denali-gost-db
networks:
    frontend:
        ipam:
            driver: default
            config:
                - subnet: "172.120.0.0/16"
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.121.0.0/16"
